### ISSUE TITLE
GER as input feature

### ISSUE THREAD

**Issue by tianyu-LL** [qcri/e-wer#1]
hi, I think use GER as input feature does not make sense here, since we can't get it without reference transcription. GER and WER are kind of same thing, right?

**Comment by amali** [comment]
This is not true, the GER is based on aligning the results for the LVCSR with the results from the grapheme recognition systems. For more details look at Table10.1 here https://www.era.lib.ed.ac.uk/bitstream/handle/1842/31224/Ali2018.pdf?sequence=1&isAllowed=y

**Comment by tianyu-LL** [comment]
ok I get it, thank you!
